version: "3.91"

services:
  slack:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m app.slack
    ports:
      - "3002:3002"
    volumes:
      - ./app:/app/app
      - ./data/sqlite3:/app/data/sqlite3